version: "3.9"

services:
  db:
    image: postgres:15
    container_name: paris_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paris
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: paris_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/paris?sslmode=disable"
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app
    restart: on-failure
  frontend:
    image: nginx:alpine
    platform: linux/arm64
    container_name: paris_frontend
    volumes:
     - ./frontend:/usr/share/nginx/html:ro
    ports:
     - "8080:80"

volumes:
  db_data:
